In [3]:
import numpy as np
a = np.array([1,2,3,4])
print("matrix 1:\n", a)
b = np.array([5,6,7,8])
print("matrix 2:\n", b)
c = a+b
print("matrix on adding 1 and 2 is:\n", c)

matrix 1:
 [1 2 3 4]
matrix 2:
 [5 6 7 8]
matrix on adding 1 and 2 is:
 [ 6  8 10 12]
